# Generated by Django 4.0.1 on 2022-02-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
