# Generated by Django 4.0.1 on 2022-03-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0, max_length=30, null=True)),
                ('payment_method', models.CharField(max_length=30, null=True)),
                ('payment_status', models.CharField(choices=[('None', 'None'), ('Incomplete', 'Incomplete'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='None', max_length=30, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.order')),
            ],
        ),
    ]
