# Generated by Django 4.0.1 on 2022-03-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
