# Generated by Django 4.0.1 on 2022-03-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
