# Generated by Django 4.0.1 on 2022-03-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_payments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('UserCancelled', 'UserCancelled'), ('Placed', 'Placed'), ('Out Of Delevery', 'Out Of Delevery'), ('Return', 'Return')], default='New', max_length=200, null=True),
        ),
    ]
