# Generated by Django 4.0.1 on 2022-03-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyNow',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('shipped', 'shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('UserCancelled', 'UserCancelled'), ('Out Of Delevery', 'Out Of Delevery'), ('Return', 'Return')], default='New', max_length=200, null=True),
        ),
    ]
