# Generated by Django 4.0.1 on 2022-03-12 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_order_buynow_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Normal', 'Normal'), ('ReferredTo', 'ReferredTo'), ('ReferredBy', 'ReferredBy')], max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('available', models.BooleanField(default=True, null=True)),
                ('proceed', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
