# Generated by Django 4.0.1 on 2022-03-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_signupcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupen',
            field=models.IntegerField(null=True),
        ),
    ]
