# Generated by Django 4.0.1 on 2022-03-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_order_coupen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
