# Generated by Django 4.0.1 on 2022-03-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_coupen'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
