# Generated by Django 4.0.1 on 2022-03-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_category_category_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_off',
            field=models.IntegerField(default=0),
        ),
    ]
