# Generated by Django 4.0.1 on 2022-04-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_alter_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('shipped', 'shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('UserCancelled', 'UserCancelled'), ('Out Of Delevery', 'Out Of Delevery'), ('Return', 'Return')], default='Placed', max_length=200, null=True),
        ),
    ]
