# Generated by Django 4.0.1 on 2022-04-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
