# Generated by Django 4.0.1 on 2022-04-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_alter_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(max_length=20, null=True),
        ),
    ]
